apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
  name: zipkin
  namespace: zipkin
spec:
  ports:
  - name: http
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: zipkin-collector
  type: LoadBalancer 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin-ui
  name: zipkin-ui
  namespace: zipkin
spec:
  ports:
  - name: http
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: zipkin-ui
  type: LoadBalancer 
