apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql
  namespace: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    role: master
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql-headless
  namespace: postgresql
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql-read
  namespace: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    release: postgresql
    role: slave
  type: LoadBalancer 
