---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 32g-postgresql-data-pv-0
  namespace: postgresql 
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-05.com.stundzia:NAS1.postgresql-data-0 
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: postgresql 
    name: data-postgresql-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 32g-postgresql-data-pv-1
  namespace: postgresql
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-05.com.stundzia:NAS1.postgresql-data-1
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: postgresql
    name: data-postgresql-slave-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 32g-postgresql-data-pv-2
  namespace: postgresql
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-05.com.stundzia:NAS1.postgresql-data-2
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: postgresql
    name: data-postgresql-slave-1 

