apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: metallb-config 
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.5.100-192.168.5.199
    - name: public 
      protocol: layer2
      addresses:
      - 192.168.5.50-192.168.5.99
      auto-assign: false
    - name: private
      protocol: layer2
      addresses:
      - 192.168.5.200-192.168.5.250
      auto-assign: false
