apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
  name: jaeger-agent
  namespace: jaeger
spec:
  ports:
  - name: agent-zipkin-thrift
    port: 5775
    protocol: UDP
  - name: agent-compact
    port: 6831
    protocol: UDP
  - name: agent-binary
    port: 6832
    protocol: UDP
  - name: agent-sampling
    port: 5778
    protocol: TCP
  selector:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
  name: jaeger-collector
  namespace: jaeger
spec:
  ports:
  - name: jaeger-collector-tchannel
    port: 14267
    protocol: TCP
  - name: jaeger-collector-http
    port: 14268
    protocol: TCP
  - name: jaeger-collector-zipkin
    port: 9411
    protocol: TCP
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
  type: LoadBalancer 
  loadBalancerIP: 192.168.5.212
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    component: client
    release: jaeger
  name: jaeger-elasticsearch-client
  namespace: jaeger
spec:
  clusterIP: 10.107.225.187
  ports:
  - name: http
    port: 9200
    protocol: TCP
  selector:
    app: elasticsearch
    component: client
    release: jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    component: master
    release: jaeger
  name: jaeger-elasticsearch-discovery
  namespace: jaeger
spec:
  clusterIP: None
  ports:
  - port: 9300
    protocol: TCP
    targetPort: transport
  selector:
    app: elasticsearch
    component: master
    release: jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
  name: jaeger-query
  namespace: jaeger
spec:
  ports:
  - name: jaeger-query
    port: 16686 
    protocol: TCP
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    component: nginx
  name: jaeger
  namespace: jaeger
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: jaeger
    component: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.5.213

