---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 100g-jaeger-data-pv-0
  namespace: jaeger
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.jaeger-data-0
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain 
  claimRef:
    namespace: jaeger 
    name: data-jaeger-elasticsearch-master-0 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 100g-jaeger-data-pv-1
  namespace: jaeger
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.jaeger-data-1
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jaeger
    name: data-jaeger-elasticsearch-master-1 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 100g-jaeger-data-pv-2
  namespace: jaeger
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.jaeger-data-2
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jaeger
    name: data-jaeger-elasticsearch-master-2 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 100g-jaeger-data-pv-3
  namespace: jaeger
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.jaeger-data-3
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jaeger
    name: data-jaeger-elasticsearch-data-0 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 100g-jaeger-data-pv-4
  namespace: jaeger
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.jaeger-data-4
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jaeger
    name: data-jaeger-elasticsearch-data-1
---

