apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    component: client
    release: jaeger
  name: jaeger-elasticsearch-client
  namespace: jaeger
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    component: data
    release: jaeger
  name: jaeger-elasticsearch-data
  namespace: jaeger
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    component: master
    release: jaeger
  name: jaeger-elasticsearch-master
  namespace: jaeger
