---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 500g-prometheus-data-pv
  namespace: monitoring 
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.prometheus-data 
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain 
  claimRef:
    namespace: monitoring 
    name: prometheus-data-dir 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 50g-prom-alertmanager-pv
  namespace: monitoring 
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.prometheus-alertmanager-data
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain 
  claimRef:
    namespace: monitoring 
    name: prometheus-alertmanager-dir
---
