apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    component: server
  name: prometheus-server
  namespace: monitoring 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: prometheus-alertmanager
  namespace: monitoring 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    component: kube-state-metrics
  name: prometheus-kube-state-metrics
  namespace: monitoring 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    component: node-exporter
  name: prometheus-node-exporter
  namespace: monitoring 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    component: pushgateway
  name: prometheus-pushgateway
  namespace: monitoring 
