apiVersion: v1
kind: Service
metadata:
  name: pihole 
  namespace: pihole 
  labels:
    app: pihole
    kubernetes.io/name: "pihole"
  annotations:
    metallb.universe.tf/address-pool: private
spec:
  selector:
    app: pihole 
  type: LoadBalancer
  loadBalancerIP: 192.168.5.202
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
  - name: pihole-https
    port: 443
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: private
    metallb.universe.tf/allow-shared-ip: pihole
  labels:
    app: pihole
    kubernetes.io/name: "pihole"
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 192.168.5.204 
  ports:
  - name: pihole-dns
    port: 53
    protocol: UDP 
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-blackhole
  namespace: pihole
  labels:
    app: pihole-blackhole
    kubernetes.io/name: "pihole-blackhole"
  annotations:
    metallb.universe.tf/address-pool: private
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 192.168.5.204
  ports:
  - name: pihole-http
    port: 80
    targetPort: 20
  - name: pihole-https
    port: 443
    targetPort: 20

