---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 75g-pihole-config-pv
  namespace: pihole
spec:
  capacity:
    storage: 75Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-07.com.stundzia:NAS1.pihole-config 
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: pihole 
    name: pihole-config-dir
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 75g-pihole-dns-config-pv
  namespace: pihole
spec:
  capacity:
    storage: 75Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.pihole-dns-config 
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: pihole
    name: pihole-dns-config-dir
---

