apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-dir
  namespace: pihole 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 75Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dns-config-dir
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 75Gi

