---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 50g-grafana-data-pv 
  namespace: plex
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-05.com.stundzia:NAS1.grafana-data-dir
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: grafana 
    name: grafana-data-dir
