---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-dir
  namespace: grafana 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
