---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1500g-docker-registry-pv
  namespace: docker-registry 
spec:
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.docker-registry-data 
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: docker-registry
    name: docker-registry-data 
---
