apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-data 
  namespace: docker-registry 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi 
---
