apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: docker-ui
  name: docker-ui
  namespace: docker-registry
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: docker-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docker-ui
    spec:
      containers:
      - name: docker-ui
        env:
        - name: REGISTRY_URL
          value: "https://docker.stundzia.com:443"
        - name: REGISTRY_TITLE
          value: "docker.stundzia.com"
        - name: DELETE_IMAGES
          value: "true"
        image: joxit/docker-registry-ui:static
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
