apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: jenkins
  type: LoadBalancer
  loadBalancerIP: 192.168.5.217
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-agent
  namespace: jenkins
spec:
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
  selector:
    app: jenkins
  type: ClusterIP
