---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 50g-jenkins-home-pv
  namespace: jenkins 
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.jenkins-home-data 
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jenkins 
    name: jenkins-home-dir 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 50g-jenkins-config-pv
  namespace: jenkins
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.jenkins-config-data
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jenkins
    name: jenkins-config-dir
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 50g-jenkins-plugins-pv
  namespace: jenkins
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.jenkins-plugins-data
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jenkins
    name: jenkins-plugins-dir
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 50g-jenkins-secrets-pv
  namespace: jenkins
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.jenkins-secrets-data
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jenkins
    name: jenkins-secrets-dir
---

