apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-dir
  namespace: jenkins 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-config-dir
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-plugins-dir
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-secrets-dir
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
---

