apiVersion: v1
kind: Service
metadata:
  labels:
    app: artifactory
  name: artifactory
  namespace: artifactory
spec:
  ports:
  - name: artifactory
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: artifactory
    component: artifactory
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: artifactory
  name: artifactory-nginx
  namespace: artifactory
spec:
  ports:
  - name: artifactoryhttps
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: artifactory
    component: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.5.218
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: artifactory-postgresql
  name: artifactory-postgresql
  namespace: artifactory
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: artifactory-postgresql
  type: ClusterIP
