---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 100g-artifactory-postgres-pv
  namespace: jenkins 
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.artifactory-postgres-data 
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: artifactory
    name: artifactory-postgres-dir 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1500g-artifactory-data-pv
  namespace: artifactory 
spec:
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.artifactory-data
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: artifactory
    name: artifactory-data-dir
---

