apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-postgres-dir
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-data-dir
  namespace: artifactory 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
---
