apiVersion: v1
data:
  master-key: FFFF==
kind: Secret
metadata:
  labels:
    app: artifactory
  name: artifactory
  namespace: artifactory
type: Opaque
---
apiVersion: v1
data:
  postgres-password: FFFF==
kind: Secret
metadata:
  labels:
    app: artifactory-postgresql
  name: artifactory-postgresql
  namespace: artifactory
type: Opaque
