apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
    kubernetes.io/name: "mysql"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.5.100
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin 
  namespace: mysql
  labels:
    app: phpmyadmin 
    kubernetes.io/name: "phpmyadmin"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.5.101 
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpmyadmin 

