apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1000g-mysql-pv
  namespace: mysql 
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-05.com.stundzia:NAS1.mysql-data
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mysql 
    name: mysql-data-dir
