---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-dir
  namespace: mysql 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
