apiVersion: v1
kind: Service
metadata:
  name: ark
  namespace: ark
  annotations:
    metallb.universe.tf/allow-shared-ip: ark
    metallb.universe.tf/address-pool: public
  labels:
    app: ark
    kubernetes.io/name: "ark"
spec:
  selector:
    app: ark
  type: LoadBalancer
  loadBalancerIP: 192.168.5.51 
  ports:
  - name: ark-rcon
    port: 32330
    protocol: TCP
  - name: ark-tcp
    port: 27015
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ark-udp
  namespace: ark
  annotations:
    metallb.universe.tf/allow-shared-ip: ark
    metallb.universe.tf/address-pool: public
  labels:
    app: ark
    kubernetes.io/name: "ark"
spec:
  selector:
    app: ark
  type: LoadBalancer
  loadBalancerIP: 192.168.5.51 
  ports:
  - name: ark-main-udp
    port: 27015
    protocol: UDP
  - name: ark-game-udp
    port: 7777
    protocol: UDP 
  - name: ark-raw-udp
    port: 7778
    protocol: UDP

