---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 250g-ark-game-pv
  namespace: lidarr
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-08.com.stundzia:NAS1.ark-game-data 
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: ark 
    name: ark-game-dir 

