apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-game-dir
  namespace: ark 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 250Gi 
