---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 32g-cassandra-data-pv-0
  namespace: cassandra 
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-05.com.stundzia:NAS1.cassandra-data-0 
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: cassandra 
    name: data-cassandra-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 32g-cassandra-data-pv-1
  namespace: cassandra
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-05.com.stundzia:NAS1.cassandra-data-1
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: cassandra 
    name: data-cassandra-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 32g-cassandra-data-pv-2
  namespace: cassandra
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.5.10:3260
    portals: ['192.168.5.10:3260']
    iqn: iqn.2000-05.com.stundzia:NAS1.cassandra-data-2
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
       name: chap-secret
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: cassandra 
    name: data-cassandra-2 

